name: CI
on: push
env:
  NODE_ENV: "development"
  YARN_CACHE_FOLDER: ${{ github.workspace }}/.cache/yarn
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn build